// Generated by CoffeeScript 1.7.1
(function() {
  var Essay, createAndAdd, populateDB;

  Essay = require('../schemas/schemas').EssayGrades;

  Essay.count({}, function(err, c) {
    if (err) {
      console.log(err);
    }
    if (c === 0) {
      console.log('Populating database');
      return populateDB();
    }
  });

  exports.findAllEssays = function(req, res) {
    return Essay.find(function(err, items) {
      console.log("Calling findAllEssays");
      return res.send(items);
    });
  };

  exports.create = function(req, res) {
    var newEssayGrade;
    newEssayGrade = new Essay(req.body);
    console.log('created essay grade for ' + newEssayGrade.Author);
    newEssayGrade.save();
    return res.send();
  };

  exports.getByAuthor = function(req, res) {
    var id;
    id = req.route.params['Author'];
    return Essay.findById(id, function(err, result) {
      return res.send(result);
    });
  };

  populateDB = function() {
    var Essays, EssaysArray, _i, _len, _results;
    EssaysArray = [
      {
        Grader: 'Justin',
        Author: 'David',
        Grades: ['A'],
        EssayTexts: ['My Essay Sucks']
      }
    ];
    _results = [];
    for (_i = 0, _len = EssaysArray.length; _i < _len; _i++) {
      Essays = EssaysArray[_i];
      _results.push(createAndAdd(Essays));
    }
    return _results;
  };

  createAndAdd = function(sec) {
    var newEssays;
    newEssays = new Essay(sec);
    return newEssays.save();
  };

}).call(this);

//# sourceMappingURL=essayRoute.map
