// Generated by CoffeeScript 1.7.1
(function() {
  var Essay, authorName, authorToken;

  Essay = require('../schemas/schemas').EssayGrades;

  authorName = "";

  authorToken = "";

  exports.index = function(req, res) {
    Essay.find(function(err, items) {
      var i, itemAuthor;
      console.log("Calling findAllEssays");
      items;
      itemAuthor = [];
      i = 0;
      while (i < items.length) {
        itemAuthor[i] = items[i].Author;
        i++;
      }
      return console.log(itemAuthor);
    });
    res.render("index", {
      title: "Lightside",
      author: res.author,
      token: ""
    });
  };

}).call(this);

//# sourceMappingURL=index.map
