// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    res.render("index", {
      title: "yo yo yo yo dis b"
    });
  };

}).call(this);

//# sourceMappingURL=index.map
